### ISSUE TITLE
More explanation about virt-backup

### ISSUE THREAD

**Issue by deajan** [aruhier/virt-backup#30]
Hello,

I stumbled on your repo while searching for a quick and dirty lab kvm backup solution.
I read the docs, but couldn't find out whether virt-backup does incremental / differential / only complete backup jobs.

Unless I didn't read well, would you mind improving the docs by adding a quick "what it does / how it works" section ?

Best regards.

**Comment by aruhier** [comment]
Hi,
Thanks a lot for this request, and I completely agree with you, and already created an issue for myself about that (see issue #10).

I'm closing this one as it's a duplicate.

**Comment by aruhier** [comment]
Oh and to answer to your question: virt-backup doesn't do incremental backups. You can do incremental backups if you have deduplication in your filesystem, but virt-backup does not handle that.

It's something that could be added, though, now that I split the way I store the backups into "packagers", there could be a packager handling some deduplication. However I didn't start to do it, and wanted to work on other issues before.
