### ISSUE TITLE
Suggestion: Quisce option

### ISSUE THREAD

**Issue by darkobas** [aruhier/virt-backup#34]
Hi

if you could consider maybe addiing a quisce option to snapshot creation

VIR_DOMAIN_SNAPSHOT_CREATE_QUIESCE

regards

**Comment by aruhier** [comment]
Hi,
That's indeed a great I didn't know that this option exists. The only issue I'll need to workaround is that the snapshot is going to fail with this option if no guest agent is running on the VM, so I need to keep the current way as fallback.

It shouldn't be such an issue, though.

**Comment by darkobas** [comment]
maybe adding a config option would suffice

great scripts btw, best I could find

**Comment by aruhier** [comment]
Yeah, I wanted to have it as an option, but also avoiding to crash on a backup if the domain is not compatible. I'll probably split the work anyway, so you'll be able to test it if you want.

Thanks for the compliment! I try to improve it by working on some documentation, from time to time, in order to be more transparent what this tool is doing.

**Comment by deajan** [comment]
+1 for quiescence support :)

**Comment by darkobas** [comment]
> +1 for quiescence support :)

U can just add to snapshot.py under METADATA
VIR_DOMAIN_SNAPSHOT_CREATE_QUIESCE

**Comment by aruhier** [comment]
I'll probably work on it this week end.

As I said, it's not really just adding this metadata, as I have to write a fallback mechanism, but yes if you want to patch it for now, you can do that. Just make sure that all your VMs have a guest agent running, otherwise the backup will fail.

**Comment by deajan** [comment]
@darkobas Thanks, but quiescence may fail even when qemu-guest-agent is installed, depending on the underlying pre-freeze, post-thaw scripts timeouts, or VSS environment timeouts.
In that case, I'd still would like to have non quiesce backups ;)
@aruhier That would be terrific.
Do you have any sponsor/donation page where one could buy you some coffee / beer ? I am seeking to use virt-backup for my personal kvm setups, and am willing to contribute with code and/or finances.

**Comment by aruhier** [comment]
As promised, you can test it via the `quiesce` branch: https://github.com/aruhier/virt-backup/tree/quiesce

I'll do some testing on a real hypervisor, but you can already test it if you want and report me any bug you can find. Please set virt-backup in debug so I will be able to get a bit more info.

You can enable the quiesce option in the config: https://github.com/aruhier/virt-backup/blob/a6bc4f2ed65ad7b80fcbbc32de6b1c406bc10a02/example/config.yml#L102
It is also configurable per host definition, and it overrides the default group option (I added an example for it).

It should also handle the failures pretty well and fallback on a "normal" (without quiesce) snapshot. Please feel free to tell me if it's not the case.

**Comment by aruhier** [comment]
> Do you have any sponsor/donation page where one could buy you some coffee / beer ? I am seeking to use virt-backup for my personal kvm setups, and am willing to contribute with code and/or finances... or worse... documentation updating ;)

It's really nice to ask, and thanks a lot for that, but I don't have anything for donations, and honestly don't want and need it. This project, as others, is something I maintain on my personal side, and I don't want to feel any pressure to work on it because of donations.

However, I would really be happy about any contribution. I'm writing some documentation, more user focused but it explains the different mechanism of virt-backup. I only do that from time to time, so I don't know when I will be done with that.

**Comment by deajan** [comment]
@aruhier No worries, I am just glad someone has solved a problem I am facing right now, so that deserves beer/coffee ;)
I will test the quiesce branch today and report back if I find something strange.

**Comment by deajan** [comment]
Had a test run today, so far quiescence works, fallback works too :)
The only trouble I had was disabling quiescence per host, which didn't work.
Even when I comment out any other host except my test host (which is a FreeBSD based appliance, sure to fail with quiescence), I get the following output:

```
opnsense.tlb.local: Backup started
libvirt: QEMU Driver error : Guest agent is not responding: QEMU guest agent is not connected
('opnsense.tlb.local: snapshot with Quiesce required, but failed. It can be due to the lack of a QEMU guest agent running inside the VM. Retrying without Quiesce.',)
opnsense.tlb.local: Backup disk sda
```

My config file:

```
---


debug: False

threads: 4



uri: "qemu:///system"

username:
passphrase:




default:
  daily: 1

groups:
  test:
    target: /data/backups

    packager: zstd

    packager_opts:
      compression_lvl: 5

    autostart: True

    daily: 1


    quiesce: True


    hosts:
      - host: opnsense.warp.local
        quiesce: False

      # - "r:^.*"

```

**Comment by aruhier** [comment]
Indeed, I forgot to use this option for specific domains.

@deajan: can you try again and tell me if it's fine?

**Comment by deajan** [comment]
Updated the code to latest git commit on branch quiese. Still the same behavior.

```
libvirt: QEMU Driver error : Guest agent is not responding: QEMU guest agent is not connected
('supervision.mach.local: snapshot with Quiesce required, but failed. It can be due to the lack of a QEMU guest agent running inside the VM. Retrying without Quiesce.',)
libvirt: QEMU Driver error : Guest agent is not responding: QEMU guest agent is not connected
('opnsense.mach.local: snapshot with Quiesce required, but failed. It can be due to the lack of a QEMU guest agent running inside the VM. Retrying without Quiesce.',)
```

My config.yaml file did not change, except that I obviously had to uncomment the last line in order to get my other VMs backed up.

**Comment by aruhier** [comment]
Thanks, I'll try to push the tests more on my side. And more globally I'll try to allocate for time for virt-backup these days.

**Comment by deajan** [comment]
Thanks for your work.
